name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00
  push:
    branches:
      - main # Replace with your default branch if not "main"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install fortune and cowsay
        run: sudo apt-get update && sudo apt-get install -y fortune cowsay

      - name: Run fortune | cowsay and update README.md
        run: |
          OUTPUT=$(fortune | cowsay)
          ESCAPED_OUTPUT=$(echo "$OUTPUT" | sed 's/`/\\`/g')  # Escape backticks in the output
          WRAPPED_OUTPUT="\`\`\`\n$ESCAPED_OUTPUT\n\`\`\`"  # Wrap the output in triple backticks
          echo "$WRAPPED_OUTPUT"

          START="<!--START_SECTION:cowsay-->"
          END="<!--END_SECTION:cowsay-->"
          TMP_FILE=$(mktemp)

          awk -v start="$START" -v end="$END" -v new_content="$OUTPUT" \
          'BEGIN {p=1} \
          $0 == start {print; print new_content; p=0} \
          $0 == end {p=1} \
          p' README.md > "$TMP_FILE"

          mv "$TMP_FILE" README.md

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          git commit -m "Update README with new cowsay fortune"
          git push
