name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at 00:00
#   push:
#     branches:
#       - main # Replace with your default branch if not "main"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Install fortune and cowsay
        run: sudo apt-get update && sudo apt-get install -y fortune cowsay

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run Python script to update README.md
        run: python update_readme.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add README.md
          if git commit -m "Update README with new cowsay fortune"; then
            git push
          else
            echo "No changes to commit"
          fi
